name: ChunkLoaders
version: '1.0-SNAPSHOT'
main: im.sooooubway.chunkloaders.ChunkLoaders
api-version: '1.20'
commands:
  chunkloaders:
    description: Get chunk loaders here
    aliases: [cl, chunkloader]